jshint:
  config_file: .jshintrc
  ignore_file: .javascript_ignore
  enabled: false
eslint:
  config_file: .eslintrc
  ignore_file: .eslintignore
  enabled: true
scss:
  config_file: .scss-lint.yml
  enabled: true
